packages:
  - "apps/*"
  - "libs/*"

autoInstallPeers: true

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - nx
  - prisma
  - sharp
  - unrs-resolver
